server.port=8082
logging.level.org.springframework=debug
# Replace ResourceBundleMessageSource in Java code
spring.messages.basename=messages
# Use set username and password for spring-boot-starter-security
# Replace security token generated during application build
spring.security.user.name=kuntal
spring.security.user.password=pass1234
springdoc.api=/api-docs