logging.level.org.springframework=info
# Keep database URL constant
spring.datasource.url=jdbc:h2:mem:testdatabase
spring.data.jpa.repositories.bootstrap-mode=default
# Log SQL statements
spring.jpa.show-sql=true
# localhost:8080/h2-console
spring.h2.console.enabled=true