services:

  postgres:
    image: postgres:16
    container_name: shared-postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: cache-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rmq_user
      RABBITMQ_DEFAULT_PASS: rmq_pass

  ibm-mq:
    image: theencodedbong/ibm-mq-arm64:latest
    container_name: ibm-mq
    ports:
      - "1414:1414"
      - "9443:9443"
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"
      MQ_ADMIN_PASSWORD: "admin123!"
      MQ_APP_PASSWORD: "app123!"
    volumes:
      - qm1data:/mnt/mqm
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9443" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
  qm1data: