server:
  port: 8082

spring:
  jms:
    pub-sub-domain: false
    template:
      default-destination: TEB.MSG.QUEUE
  sleuth:
    propagation:
      type: w3c

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false