server:
  port: 8082

spring:
  jms:
    pub-sub-domain: false
    template:
      default-destination: TEB.MSG.QUEUE
  sleuth:
    propagation:
      type: w3c

ibm:
  mq:
    host: localhost
    port: 1414
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    username: app
    password: app123!

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
      enabled: false
  sdk:
    disabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false