-- 1) MFA disabled user
-- 2) MFA enabled user

insert into users (username,
                   email,
                   password,
                   enabled,
                   role,
                   account_non_locked,
                   failed_attempts,
                   locked_until,
                   mfa_enabled,
                   mfa_secret,
                   created_at,
                   updated_at)
values ('no_mfa_user',
        'austin316@email.com',
        '$2a$10$adr8aQjI3.CDswfdUQuwDOzmTt1nWdmFcq4ddZLxb9HTkOeH6Q2/y',
        true,
        'USER',
        true,
        0,
        NULL,
        false,
        NULL,
        NOW(),
        NOW());
insert into users (username,
                   email,
                   password,
                   enabled,
                   role,
                   account_non_locked,
                   failed_attempts,
                   locked_until,
                   mfa_enabled,
                   mfa_secret,
                   created_at,
                   updated_at)
values ('mfa_user',
        'ucantcme@email.com',
        '$2a$10$adr8aQjI3.CDswfdUQuwDOzmTt1nWdmFcq4ddZLxb9HTkOeH6Q2/y',
        true,
        'USER',
        true,
        0,
        NULL,
        true,
        'O5TU6FH3OTRP73ILAEPNMGAY3EBLVOZF',
        NOW(),
        NOW());
