server:
  port: 8080

spring:
  jms:
    pub-sub-domain: false

ibm:
  mq:
    queueManager: QM1
    channel: DEV.APP.SVRCONN
    connName: localhost(1414)
    user: app
    password: app123!

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false