server:
  port: 8080

spring:
  jms:
    pub-sub-domain: false

ibm:
  mq:
    host: localhost
    port: 1414
    queue-manager: QM1
    channel: DEV.APP.SVRCONN
    username: app
    password: app123!

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false